Repository cyclus/cyclus, pull requests merged in 2024-04, with the labels that each got.

#1706 Remove smbchk for new release
  CHANGELOG.rst
  release/smbchk.py
  tests/test_abi.py
  tests/test_smbchk.py
Labels: Release

#1715 Small documentation fixes
  CHANGELOG.rst
  CONTRIBUTING.rst
  INSTALL.rst
  README.rst
Labels: Documentation

#1740 add --allow-milps flag for install
  CHANGELOG.rst
  INSTALL.rst
Labels: Documentation

#1729 Package management by context and handling of repackaging process
  CHANGELOG.rst
  src/context.cc
  src/package.cc
  src/package.h
  src/product.cc
  src/resource.h
  src/xml_file_loader.cc
  tests/resource_tests.cc
Labels: Defect
