Repository cyclus/cyclus, pull requests merged in 2025-07, with the labels that each got.

#1870 Calculate Bid Cost
  CHANGELOG.rst
  src/economic_entity.h
  src/toolkit/facility_cost.cycpp.h
  src/toolkit/institution_cost.cycpp.h
  src/toolkit/region_cost.cycpp.h
Labels: Feature

#1867 Update Definition of a Year to be Gaussian (+4s)
  CHANGELOG.rst
  src/context.h
Labels: Maintenance

#1877 Calculate Unit Price
  CHANGELOG.rst
  src/toolkit/facility_cost.cycpp.h
Labels: Feature

#1856 Fix cycstub caps
  CHANGELOG.rst
  CONTRIBUTING.rst
  DEPENDENCIES.rst
  INSTALL.rst
  README.rst
  stubs/README.rst
  stubs/example_facility.xml
  stubs/example_inst.xml
  stubs/example_region.xml
  tests/test_stubs.py
Labels: Defect
